### ISSUE TITLE
No Functionality aka Index.php or Controlls

### ISSUE THREAD

**Issue by Dranos-Nupper** [WoWTech/unnamed-cms-releases#1]
![noindex](https://user-images.githubusercontent.com/6026902/28888351-339d03f4-77b8-11e7-8f17-6c0a7e52a550.png)

**Comment by WoWTech** [comment]
**index.php** file is in the [public ](https://github.com/WoWTech/unnamed-cms-releases/tree/master/public) folder.

Please, be sure to checkout paragraph **4** of [Installation](https://github.com/WoWTech/unnamed-cms-releases#installation) guide.
