### ISSUE TITLE
Root dir

### ISSUE THREAD

**Issue by Viste** [WoWTech/unnamed-cms-releases#2]
How i can use public_html againt public.
I need it becouse my site is place on free hosting and server running in another place and on hosting i can't change root dir in apache settings

**Comment by Viste** [comment]
Close it plz. I found needed in filesystem.php

**Comment by WoWTech** [comment]
Такой способ возможен, но лучше использовать мануалы, доступные в интернете по поисковому запросу "laravel on shared hosting". Так же, можете писать тикеты по русски, если вам так удобнее.

**Comment by Viste** [comment]
@WoWTech я разобрался без гайдов )) пхп похож на С++ не составило особо труда, спасибо за фреимворк жду новых обновлений! И сделай какой-то кошелек для пожертвований, как будут свободные деревенные скину за твой труд
