### ISSUE TITLE
Мультиреалмовость

### ISSUE THREAD

**Issue by Viste** [WoWTech/unnamed-cms-releases#6]
Можно ли получить краткую ифну как завести фреимворк на 3 реалма

**Comment by WoWTech** [comment]
Что именно вы хотите узнать? Имеете ли вы в виду добавить дополнительные реалмы в нашу CMS или сам фреймворк Laravel?

**Comment by Viste** [comment]
Ну получается что цмска с фреимворком тут единое целое, хочется понять откуда отталкиваться чтобы начать понимать как сделать поддержку 2-3 реалмов.

**Comment by WoWTech** [comment]
Данная опция не доступна по умолчанию из-за не предусмотренного места под другие реалмы в дизайне сайта. Но вы можете сами модифицировать скрипты для поддержки "мультиреалмности".
Файлы, которые (в том числе) нужно будет изменить:
https://github.com/WoWTech/unnamed-cms-releases/blob/master/app/Services/Server.php
https://github.com/WoWTech/unnamed-cms-releases/blob/master/config/server.php

**Comment by Viste** [comment]
Можно на ты я не такой старый и известный ))

**Comment by Viste** [comment]
Спасибо посмотрим подумаем
отпишусь

**Comment by Viste** [comment]
жду не дождусь форум
